id: opecha:P000406
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC466
  title: 'བོད་བརྒྱུད་ནང་བསྟན་གྱིས་བོད་ཀྱི་སྲོལ་རྒྱུན་སྲིད་ཁྲིམས་གྱི་ངོ་བོ་དང་ད་སྔའི་གནས་སྟངས་ལ་ཤུགས་རྐྱེན་ཐེབས་པའི་སྐོར་ལ་ཅུང་ཙམ་དཔྱད་པ། '
  volume:
    8574faea71b84d5b98c2a15f54a9c04d:
      image_group_id: I2PD18735
      title: Volume 1 of bod brgyud nang bstan gyis bod kyi srol rgyun srid khrims
        gyi ngo bo dang da snga'i gnas stangs la shugs rkyen thebs pa'i skor la cung
        tsam dpyad pa/
      volume_number: 1
      total_pages: 228
  author: ''
ebook_metadata:
  title: 'བོད་བརྒྱུད་ནང་བསྟན་གྱིས་བོད་ཀྱི་སྲོལ་རྒྱུན་སྲིད་ཁྲིམས་གྱི་ངོ་བོ་དང་ད་སྔའི་གནས་སྟངས་ལ་ཤུགས་རྐྱེན་ཐེབས་པའི་སྐོར་ལ་ཅུང་ཙམ་དཔྱད་པ། '
  author: ''
  sku: P000406
  cover: cover.jpg
  layers:
  - pagination
