id: P000406
initial_creation_type: ocr
created_at: 17/03/2020
last_modified_at: 2021-12-16 15:38:18.993332
source_metadata:
  id: bdr:W1AC466
  title: 'བོད་བརྒྱུད་ནང་བསྟན་གྱིས་བོད་ཀྱི་སྲོལ་རྒྱུན་སྲིད་ཁྲིམས་གྱི་ངོ་བོ་དང་ད་སྔའི་གནས་སྟངས་ལ་ཤུགས་རྐྱེན་ཐེབས་པའི་སྐོར་ལ་ཅུང་ཙམ་དཔྱད་པ། '
  author: ''
  volumes:
    8574faea71b84d5b98c2a15f54a9c04d:
      image_group_id: I2PD18735
      title: Volume 1 of bod brgyud nang bstan gyis bod kyi srol rgyun srid khrims
        gyi ngo bo dang da snga'i gnas stangs la shugs rkyen thebs pa'i skor la cung
        tsam dpyad pa/
      volume_number: 1
      total_pages: 228
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
