id: opecha:P000406
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC466
  title: 'བོད་བརྒྱུད་ནང་བསྟན་གྱིས་བོད་ཀྱི་སྲོལ་རྒྱུན་སྲིད་ཁྲིམས་གྱི་ངོ་བོ་དང་ད་སྔའི་གནས་སྟངས་ལ་ཤུགས་རྐྱེན་ཐེབས་པའི་སྐོར་ལ་ཅུང་ཙམ་དཔྱད་པ། '
  volume: ''
  author: ''
